In [4]:
import numpy as np

In [16]:
L = [1,2,3,4,5]           #<<----- a list 
A = np.array([1,2,3,4,5])   #<<----- numpy 1-D array 
B = np.array([6,7,8,9,10])

## example Difference bw list and numpy_array:

print(2*L)     #<------- gives new list cotaining duplicate of list L
print(3*A)     #<------- actually multiplies each element in array by 3
#print(L**2)   #<------- Not allowed to do such operation
print(A**2)    #<------- works totally Fine!, squares each element in array

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


In [6]:
print('list:', L, '\nnumpy_array:', A)  

list: [1, 2, 3, 4, 5] 
numpy_array: [1 2 3 4 5]


In [25]:
##list = [print(i) for i in A]
"""
        Arithmetic on 1-D array
""""
print('A+B:',  A+B)
print('B-A:',  B-A)
print('2*A:',  2*A)
print('A*B:',  A*B)
print('A/2:',  A/2)
print('A**2:', A**2)   ##square of nums in array -->A

A+B: [ 7  9 11 13 15]
B-A: [5 5 5 5 5]
2*A: [ 2  4  6  8 10]
A*B: [ 6 14 24 36 50]
A/2: [0.5 1.  1.5 2.  2.5]
A**2: [ 1  4  9 16 25]


In [7]:
"""" 
        N-D ndarray     axis-0 -->cols and axis-1 -->rows
"""    
M1 = np.arange(12).reshape(3,4)
M2 = np.arange(9,21).reshape(3,4)
M3 = np.arange(12).reshape(2,3,2)
print(M1)
print()
print(M2)
print()
print(M3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [8]:
"""
        arange func 
"""
print(np.arange(9,21,2).reshape(2,3))

"""
        linspace func   --> we can specify the number of elements we want  and the step is decided automatically.
"""
print(np.linspace(5,10,10))              #<<--- 10 numbers in range 5 - 10 by default its 1-D array
print(np.linspace(0,1,12).reshape(6,2))



[[ 9 11 13]
 [15 17 19]]
[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
[[0.         0.09090909]
 [0.18181818 0.27272727]
 [0.36363636 0.45454545]
 [0.54545455 0.63636364]
 [0.72727273 0.81818182]
 [0.90909091 1.        ]]


In [9]:
"""
    Attributes of ndarray
"""
print(M1.shape, M2.shape, M3.shape)
print(M1.ndim)
print(M1.size, M2.size, M3.size)
print(M1.dtype)
#print(M1.data)
print(M1.itemsize) 

(3, 4) (3, 4) (2, 3, 2)
2
12 12 12
int32
4


In [10]:
## ravel, flat methods --> iterate over each element in ndarray/matrix
for item in M3.ravel() :   #<<-- same can be done with M3.flat
    print(item)    
    
#print(M3.flat)

0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
"""
        Arithmetic on 2-D array  -->> this will happen elementwise
"""
print(M1)
print(M2)
print('add.:\n', M1+M2)
print('sub.:\n', M2-M1)
print('mul.:\n', M1*M2)
print('div:\n',  M1/M2)

#stack m2 on m1 vertically and horizontally
print('horizontal stack:\n', np.hstack((M1,M2)))  #<<---- Note: args to stack func is tuple
print('vertical stack\n', np.vstack((M1,M2)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
add.:
 [[ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]
sub.:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
mul.:
 [[  0  10  22  36]
 [ 52  70  90 112]
 [136 162 190 220]]
div:
 [[0.         0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4        0.4375    ]
 [0.47058824 0.5        0.52631579 0.55      ]]
horizontal stack:
 [[ 0  1  2  3  9 10 11 12]
 [ 4  5  6  7 13 14 15 16]
 [ 8  9 10 11 17 18 19 20]]
vertical stack
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [12]:
"""
        MATRIX MULTIPLICATION
"""
a = np.array([[1, 2], 
     [3, 4]])

b = np.array([[9, 3], 
     [4, 5]] )

c = np.dot(a,b)

print("Matrix mul.:\n",a.dot(b))    #<<--------- This can be done by  np.dot(a,b) too!

Matrix mul.:
 [[17 13]
 [43 29]]


In [13]:
# matrix Slicing:
print('M1:\n', M1)
print('From all rows and only 1st colmn elements:\n', M1[:,1])  
print('From cols 1 and 2 and only 1st row elements:\n', M1[1,1:3])

M1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
From all rows and only 1st colmn elements:
 [1 5 9]
From cols 1 and 2 and only 1st row elements:
 [5 6]


In [244]:
#generating matrices
print('zeros:\n', np.zeros((5,5)))            #<<---- Note: argument is tuple
print()
print('ones:\n', np.ones((5,6)))
print()

#<<-----numbers bw 0 - 10----------->>#
print(10*np.random.random((5,10)))   
print()
print(np.floor(10*np.random.random((5,10))))
print()
print(np.ceil((10*np.random.random((5,10)))))

zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

ones:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[9.2976095  3.17089824 8.25579114 1.98855987 5.71381899 5.89791523
  4.45889171 0.38257608 2.88502947 1.73331424]
 [2.05035085 8.31435792 5.43834675 1.7516993  4.60140209 8.53037451
  6.26628288 2.06013363 3.18744424 2.11763293]
 [7.20769818 4.05298628 3.03650742 8.90997436 4.92149631 8.07093588
  5.16915374 4.0113633  5.44811907 9.47851791]
 [0.69622555 0.08296513 9.18703885 7.0564418  5.47029242 6.377213
  0.38580986 3.64324261 5.09861081 0.7233076 ]
 [8.23930748 7.45091632 1.96786894 8.27970888 9.72608648 6.45404085
  9.74872086 7.04930346 9.84307945 0.73130122]]

[[5. 2. 1. 4. 4. 4. 9. 3. 2. 2.]
 [8. 0. 9. 5. 9. 7. 1. 4. 1. 6.]
 [7. 8. 8. 6. 4. 9. 8. 5. 9. 0.]
 [7. 0. 1. 5. 9. 1. 7. 8. 5. 6.]
 [8. 7. 2. 9. 0. 5. 4. 1. 4. 8.]]

[[ 2.  2.  5.  1.  3.  8. 10.  5. 10.  7.]
 

In [14]:
#Some other matricx operations

print('sum of ele in M1:', M1.sum())
print('max ele in M1:', M1.max())
print('min ele in M1:',M1.min())
print('trace of mat M1:', M1.trace())
print('exp of each ele in M1:\n', np.exp(M1))
print()
print('{}\n \t+ \n {} \n \t = \n {}'.format(M1, M2, np.add(M1,M2)))
print()

# transpose
print('transpose of M1:\n',M1.T)

#inverse
print('a:\n',a)
a_inv = np.linalg.inv(a)
print('inv, of a:\n',a_inv)   #<<----- linalg(linear algebra) module

#a_inv * a -->> I (unit matrix)
print('I:\n',np.dot(a,a_inv))

#mean
print('\nmean for M1:',M1.mean())

#variance
print('variance for M1:\n',M1.var())

#standard deviation
print('standard deviation of M1:\n', np.std(M1) )

sum of ele in M1: 66
max ele in M1: 11
min ele in M1: 0
trace of mat M1: 15
exp of each ele in M1:
 [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 	+ 
 [[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 
 	 = 
 [[ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

transpose of M1:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
a:
 [[1 2]
 [3 4]]
inv, of a:
 [[-2.   1. ]
 [ 1.5 -0.5]]
I:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

mean for M1: 5.5
variance for M1:
 11.916666666666666
standard deviation of M1:
 3.452052529534663


In [223]:
#matrix operations continue'

print('a:', a)
print('determinant of a:', np.linalg.det(a))
print('diagonal elements of a:', np.diag(a))
print('diaginal matrix created:\n', np.diag([1,2,3]))   #<<--- passing 1-D array to np.diag creates diagonal matrix with 
                                                        #       off diagonal elements as zero
    
#outer product --> multiplication of each element of mat1 with each element of mat2 forms a row
print('\nouter mul:\n', np.outer([[3,4],[2,4]],
                               [[1,2], [1,3]] ))

#inner product is same as dot product    





a: [[1 2]
 [3 4]]
determinant of a: -2.0000000000000004
diagonal elements of a: [1 4]
diaginal matrix created:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

outer mul:
 [[ 3  6  3  9]
 [ 4  8  4 12]
 [ 2  4  2  6]
 [ 4  8  4 12]]
